swipe:
  3:
    left:
      command: "xdotool key super+ctrl+Right"
    right:
      command: "xdotool key super+ctrl+Left"
    up:
      command: "xdotool key super+ctrl+Down"
    down:
      command: "xdotool key super+ctrl+Up"

plugin: 
  inputs:
    libinput_command_input: # options for lib/plugin/inputs/libinput_command_input
      enable-tap: true # click to tap
      enable-dwt: true # disable tap while typing
      show-keycodes: true # https://github.com/iberianpig/fusuma-plugin-keypress#add-show-keycode-option

